### ISSUE TITLE
Audit Event Getter/Setter

### ISSUE THREAD

**Issue by lp** [bonfhir/terminology-server#13]
For the purpose of keeping track of the idempotent task execution through the server `AuditEvent`, implement a getter & a setter function storing & retrieving task types, identifiers & properties.

**Comment by biximilien** [comment]
After some testing, it seems searching by AuditEvent's agent identifier is not supported by HAPI, which is consistent with what I'm reading in the spec [](http://hl7.org/fhir/R4B/auditevent.html#search)

**Comment by biximilien** [comment]
Related issue #20
